# Generated by Django 5.1.6 on 2025-02-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
