# Generated by Django 5.1.6 on 2025-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_association_license_alter_association_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='handicaps',
            field=models.ManyToManyField(related_name='associations', to='app.handicap'),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('handicaps', models.ManyToManyField(related_name='handicaps_handicap', to='app.handicap')),
            ],
        ),
        migrations.AddField(
            model_name='handicap',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='sports_handicap', to='app.sport'),
        ),
        migrations.AddField(
            model_name='association',
            name='sports',
            field=models.ManyToManyField(related_name='associations', to='app.sport'),
        ),
    ]
